### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by jjxtra** [imazen/libwebp-net#11]
I noticed the NuGet package is from over a year ago. What needs to happen to get it updated?

**Comment by nathanaeljones** [comment]
I need to do a clean recompile of libwebp, upload it to S3, grab the hash and bytesize, inject them into an XML file, then get a Windows box working, run `.\build.cmd All`, and fix whatever has bit-rotted.

**Comment by nathanaeljones** [comment]
https://github.com/webmproject/libwebp/releases/tag/v0.5.2-rc2 

It looks like releases land within 7 days of the release candidate. Could you ping me when 0.5.2 lands? I'll update it then.

**Comment by nathanaeljones** [comment]
Built: https://ci.appveyor.com/project/imazen/libwebp/build/0.5.2.21

**Comment by nathanaeljones** [comment]
Version 10.0.1 uploaded to nuget
