### ISSUE TITLE
WebPFree only available on windows builds of libwebp

### ISSUE THREAD

**Issue by gsnerf** [imazen/libwebp-net#5]
Hi,

I realize this propably isn't your priority but using this lib on non windows systems utilizing mono fails at the moment. This is due to the fact that WebPFree is a method injected solely through the makefile for the (windows) dll version of the lib.

A good replacement would be WebPSafeFree (utils.h) which provides this function for all systems from 0.4.1 upwards.

Also providing an MSIL version of the package on NuGet (and tagging the repository with the nuget releases) would be a blast :)

**Comment by nathanaeljones** [comment]
Thanks! Sorry for the poor maintenance on this project, it's not one of my top 5 :(
