### ISSUE TITLE
SimpleEncoder/SimpleDecoder: Non-alpha encoding not correctly round-tripped

### ISSUE THREAD

**Issue by marklam** [imazen/libwebp-net#6]
I can losslessly encode an image without an alpha channel, but when decoding the data is misaligned.
The encoder [specifies the data format] (https://github.com/imazen/libwebp-net/blob/master/Imazen.WebP/SimpleEncoder.cs#L69), but the decoder [always uses BGRA] (https://github.com/imazen/libwebp-net/blob/master/Imazen.WebP/SimpleDecoder.cs#L50)

I think the problem might be due to supplying PixelFormat32... to encoding methods that expect 24bits per pixel, because I noticed that a non-alpha compression is larger than a compression with an alpha channel.

**Comment by nathanaeljones** [comment]
Would it be possible to add a failing test case for this?

**Comment by jjxtra** [comment]
This test case is still failing. I'll see if I can fix it.

**Comment by jjxtra** [comment]
Issue is fixed with commit 6257f64b0229eca5bee154ca37c13871f52207bb
