### ISSUE TITLE
Strong naming the library

### ISSUE THREAD

**Issue by 1024kilobyte** [imazen/libwebp-net#7]
Hello,

I need to use the Imazen.WebP library inside a windows service project. Therefor it needs a strong name. Even if I manage to strong name the Imazen.WebP.dll the initialization fails with:

System.IO.FileLoadException: The File or Assembly "Imazen.WebP, Version=9.0.1.0, Culture=neutral, PublicKeyToken=null" or dependency could not be found. A strong named assembly is required. (Exception HRESULT: 0x80131044)

I think this is because the libwebp.dll is not signed / strong named. Is it possible to use the library in such context?

**Comment by 1024kilobyte** [comment]
I now implemented a workaround by loading the dll at runtime, a bit of a hack, but working.

**Comment by nathanaeljones** [comment]
Thanks; we don't plan to [strong-name anything](http://strongnamingconsideredharmful.com/), but feel free to do so independently!
