### ISSUE TITLE
Calling convention is wrong

### ISSUE THREAD

**Issue by jjxtra** [imazen/libwebp-net#8]
The calling convention is defaulting to stdcall, it needs to be cdecl. This is causing stack corruption.

**Comment by nathanaeljones** [comment]
I haven't had any other reports of this. Can you verify how libwebp.dll was compiled and the platform you're seeing the failure on?

**Comment by gamedevboy** [comment]
the calling convention really needs to be cdecl, the .h contains 

> extern "C" {

**Comment by jjxtra** [comment]
I'm running on x64 not sure if it makes a difference, haven't tried on x86 machine.

**Comment by nathanaeljones** [comment]
@jjxtra While I haven't replicated this myself, I've given you push access in case you have the time to sort it out.

**Comment by jjxtra** [comment]
Thanks, I will try and push up my fixes

-- Jeff

**Comment by jjxtra** [comment]
Issue is fixed with commit 6257f64b0229eca5bee154ca37c13871f52207bb

**Comment by nathanaeljones** [comment]
Thanks! Any idea why the Xunit assemblies can't be found?

https://ci.appveyor.com/project/imazen/libwebp-net/build/0.2.0.93

**Comment by jjxtra** [comment]
I wasn't able to compile when I pulled the latest code, so I cleared out
the xunit nuget package and re-added xunit and it was able to compile and
run tests at that point.

-- Jeff

**Comment by nathanaeljones** [comment]
The [prior build](https://ci.appveyor.com/project/imazen/libwebp-net/build/0.2.0.92) was able to load them; perhaps you switched from Paket to Nuget?

**Comment by jjxtra** [comment]
Ahh that explains it, yes I used Nuget, didn't realize it was using Paket.
Let me try checking in a fix.

-- Jeff

**Comment by jjxtra** [comment]
Ok I think it's working, checked in a potential fix, let me know of any
additional problems.

-- Jeff

**Comment by jjxtra** [comment]
Looks like it worked. What needs to happen to update the .nuget package? It
is almost a year old.

-- Jeff
