### ISSUE TITLE
Is this lib AnyCPU?

### ISSUE THREAD

**Issue by xaviergonz** [imazen/libwebp-net#9]
Is this lib anycpu (this is, does it load automatically the proper dll according to the arquitecture)?
Also, do the dlls require some specific version of visual c++ runtimes?

**Comment by nathanaeljones** [comment]
On windows, it loads the appropriate dll if it is accessible. It's not a particularly sophisticated approach. I'm not sure which runtime is used, sorry! I compiled the native binaries over a year ago.

**Comment by xaviergonz** [comment]
How is "dll accessibility" determined? Can I specify a given path to look into?

**Comment by nathanaeljones** [comment]
Yeah, take a look at LoadLibrary.cs

https://github.com/imazen/libwebp-net/blob/master/src/Imazen.WebP/Extern/LoadLibrary.cs#L94
